AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A small SAM / Lambda / DynamoDB test
Resources:
  message:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.hello
      Runtime: nodejs8.10
      # The location of the code
      CodeUri: .
      Description: A small SAM / Lambda / DynamoDB test
      MemorySize: 512
      Timeout: 10
      Policies:
        # Give crud permissions to the table
        - DynamoDBCrudPolicy:
            TableName: aws-sam-test-message
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /message
            Method: ANY
  messageTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: aws-sam-test-message
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
